#!/usr/bin/env bash

# Copyright 2017 Hugo Drumond

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

SCRIPT_DIR="$(readlink -f "${0%/*}")"
ENV_FOLDER="$SCRIPT_DIR/env"
CODE_FOLDER="$SCRIPT_DIR/face_square_image"
MAIN_FILE="$CODE_FOLDER/face_square_image.py"
TEST_FOLDER="$SCRIPT_DIR/test"
REQUIREMENTS_FOLDER="$SCRIPT_DIR/requirements"

PYTHON_PATH="$(find /usr/bin/ -regex ".*/python\([0-9]\(\.[0-9]+\)*\)?$" | sort -r | head -n 1)"
if [[ -z "$PYTHON_PATH" ]]; then
  log_message "Python not found"
  exit 1
fi
PYTHON="${PYTHON_PATH##*/}"
PYTHON_VERSION="$("$PYTHON" --version | awk '{print $2}')"

REQUIREMENTS=(dev)
if [[ -n "$BUILD" ]]; then
  IFS=' ' read -r -a REQUIREMENTS <<< "$BUILD"
fi
REQUIREMENTS=(common "${REQUIREMENTS[@]}")

main() {
  if [[ $# -lt 1 ]]; then
    usage bail
  fi

  check_python_version

  local subcommand="$1"
  case "$subcommand" in
    run|env|test)
      sc_"$subcommand" "${@:2}"
      ;;
    *)
      usage bail
  esac
}

check_python_version() {
  log_message "Selected python $PYTHON_VERSION to run the app"

  IFS='.' read -r -a python_version_split <<< "$PYTHON_VERSION"

  local major="${python_version_split[0]}"
  local minor="${python_version_split[1]}"
  local patch="${python_version_split[2]}"

  if [[ "$major" -ne 3 ]]; then
    log_message 'This code was only tested on python3'
  elif [[ "$major" -eq 3 && "$minor" -lt 6 ]]; then
    log_message 'Be advised, this code was only tested on python3.6!'
  fi
}

sc_run() {
  local arguments=("$@")
  local arguments_len=$#
  local argument_separator_index=-1
  for index in "${!arguments[@]}"; do
    if [[ ${arguments[$index]} == "--" ]]; then
      argument_separator_index=$index
      break
    fi
  done

  local run_arguments=()
  local app_arguments=()
  if (( $argument_separator_index != -1 )); then
    run_arguments=("${arguments[@]::$argument_separator_index}")
    app_arguments=("${arguments[@]:$argument_separator_index+1:$arguments_len}")
  else
    run_arguments=("${arguments[@]::$arguments_len}")
  fi

  local env_arguments=()
  for run_argument in "${run_arguments[@]}"; do
    case "$run_argument" in
      -f)
        env_arguments+=("$run_argument")
        ;;
    esac
  done

  sc_env "${env_arguments[@]}"

  python "$MAIN_FILE" "${app_arguments[@]}"
}

sc_test() {
  sc_env
  python -m unittest discover -s "$TEST_FOLDER" -p "test_*.py"
}

sc_env() {
  if [[ $# -eq 1 ]]; then
    if [[ "$1" == '-f' ]]; then
      rm -rf "$ENV_FOLDER"
    fi
  fi
  if [[ ! -d "$ENV_FOLDER" ]]; then
    log_message "Creating env"
    1>&2 "$PYTHON" -m venv "$ENV_FOLDER"
    if [[ $? -ne 0 ]]; then
      log_message "Failed creating the environment"
      rm -rf "$ENV_FOLDER"
      exit 1
    fi
    source "$ENV_FOLDER/bin/activate"

    1>&2 pip install --upgrade pip

    if [[ -d "$REQUIREMENTS_FOLDER" ]]; then
        log_message "Installing requirements"
        for requirement in "${REQUIREMENTS[@]}"; do
          1>&2 pip install -r "$REQUIREMENTS_FOLDER/$requirement.txt"
        done
    else
        log_message "No requirements.txt file skipping requirements installation"
    fi
  else
    log_message 'Env already exists skipping...'
    source "$ENV_FOLDER/bin/activate"
  fi
}

usage() {
  local bail="$1"

  read -r -d '' usage_string <<EOF
[BUILD=""] $0 run [[-f] [-- ..app_arguments]] | env [-f]
 run   # runs the code
  -f              # forces env recreation and installs the requirements
  --              # separates run arguments from app arguments
  ..app_arguments # the arguments to pass to the app

  default: only creates env if it does not exist does not pass arguments to the app


 env   # creates the environment
  -f              # forces env recreation and installs the requirements

  default: only creates env if it does not exist


 BUILD # environment variable to choose the requirements to install separated by spaces, files in requirements
  common          # packages shared by all, it is added by default
  dev             # packages required for development linters, testing, etc
  ...             # check the requirements folder for the .txt files

  default: BUILD="common dev"
EOF

  log_message -e "$usage_string"

  if [[ ! -z "$bail" ]]; then
    exit 1
  fi
}

log_message() {
    1>&2 echo "$@"
}

main "$@"
